### ISSUE TITLE
Error while created complex nested class

### ISSUE THREAD

**Issue by jo8558** [appmattus/kotlinfixture#77]
I run into an issue while using fixture for created a complicated and nested class.
Unfortunately i cannot provide a lot of information apart the attached error log.
Since I'm not really able to tear down the problem the title is an assumption and the main might be something else

Until i got some information back what i can do, or maybe if a fix is necessary i have to avoid using fixture

[errorlog](https://github.com/appmattus/kotlinfixture/files/5815691/kotlinFixture_errorlog.txt)

**Comment by mattmook** [comment]
One thing you could try to help pinpoint where the exception is occuring from is to enable the logging mode, see https://github.com/appmattus/kotlinfixture/blob/main/fixture/configuration-options.adoc#logging-object-generation-with-loggingstrategy

Looking at the stack trace though it looks like one of the nested class is a Corba object that it cannot instantiate.

To fix it you may need to create a factory to help generate those objects. See https://github.com/appmattus/kotlinfixture/blob/main/fixture/configuration-options.adoc#customising-class-generation-with-factory


```
Jan 14, 2021 4:59:46 PM sun.reflect.NativeMethodAccessorImpl invoke0
WARNING: "IOP01610208: (BAD_INV_ORDER) set_result(Any) called with null args for DSI ServerRequest"
org.omg.CORBA.BAD_INV_ORDER:   vmcid: SUN  minor code: 208  completed: No
	at com.sun.corba.se.impl.logging.ORBUtilSystemException.setResultCalledNullArgs(ORBUtilSystemException.java:2107)
	at com.sun.corba.se.impl.logging.ORBUtilSystemException.setResultCalledNullArgs(ORBUtilSystemException.java:2125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
	at com.appmattus.kotlinfixture.resolver.PopulateInstance$DefaultImpls.safeCall(PopulateInstance.kt:120)
	at com.appmattus.kotlinfixture.resolver.PopulateInstance$DefaultImpls.populateJavaSetters(PopulateInstance.kt:70)
	at com.appmattus.kotlinfixture.resolver.PopulateInstance$DefaultImpls.populatePropertiesAndSetters(PopulateInstance.kt:44)
	at com.appmattus.kotlinfixture.resolver.FactoryMethodResolver.populatePropertiesAndSetters(FactoryMethodResolver.kt:30)
```
